### ISSUE TITLE
Cannot build haxall

### ISSUE THREAD

**Issue by jli113** [haxall/haxall#2] opened 2021-07-12 08:06 UTC
cannot build haxall on ubuntu in docker
error:
/root/haxall/src/lib/hxShell/fan/HxShellWeb.fan(63,7): Unknown method 'web::WebOutStream.initJs'

**Comment by mgiannini** [comment] 2021-07-12 13:35
If you are going to build Haxall from the "tip" of the development branch, then you should build your Fantom installation from the source.  Follow the [Bootstrap](https://fantom.org/doc/docTools/Bootstrap) instructions to set up yoru Fantom development environment. Then ensure the "dev" version of Fantom is in your path for building Haxall.

**Comment by jli113** [comment] 2021-07-13 01:35
I did, the annoying env and path settings, which in the end leads to this error.

**Comment by jli113** [comment] 2021-07-13 02:01
> If you are going to build Haxall from the "tip" of the development branch, then you should build your Fantom installation from the source. Follow the [Bootstrap](https://fantom.org/doc/docTools/Bootstrap) instructions to set up yoru Fantom development environment. Then ensure the "dev" version of Fantom is in your path for building Haxall.

The path is fine, it is not helping.

**Comment by mgiannini** [comment] 2021-07-13 13:19
The output in your previous comment does not look like an error. You ran `fan -version` and it correctly showed the output. I assume, based on that output, that `/root/fantom/` is your development build of Fantom from the source code? (i.e. not the unzipped distribution).  If not, then your `fan` is not pointing at the development version.

**Comment by jli113** [comment] 2021-07-14 00:57
I just downloaded and unzipped it to /root/fantom, and built an empty fan.props in /root.
Thanks for the info on slack group.

**Comment by mgiannini** [comment] 2021-07-14 01:24
> I just downloaded and unzipped it to /root/fantom, and built an empty fan.props in /root.

I assume by "downloaded" you mean you downloaded the Fantom release from the [Downloads](https://fantom.org/download) page on the Fantom website?

If so, that is not building from source. You need to follow the directions on the [Bootstrap](https://fantom.org/doc/docTools/Bootstrap) page to build Fantom from source code.

**Comment by jli113** [comment] 2021-07-14 01:50
I ran the Bootstrap, still the same error.

**Comment by mgiannini** [comment] 2021-07-14 13:57
> Does the fantom folder need to be inside haxall?
No.

After running `bootstrap.fan` you should have a directory structure similar to the one shown in the Bootstrap docs.
```
/root/rel/   # This is the latest unzipped "released" Fantom distribution from the website

/root/fan/  # This is the Git repository cloned by the <rel>/adm/bootstrap.fan script
```

To build Haxall you can force it to use the development build of Fantom by doing

```
$ cd /root/haxall/
$ /root/fan/bin/fan ./src/build.fan
```

If this works then you have successfully bootstrapped Fantom. If the following fails then your PATH `fan` is pointint to the non-development build of Fantom (i.e. `rel/` or something else)

```
$ cd /root/haxall/
$ fan src/build.fan
# or 
#./src/build.fan
```
Hopefully this helps. I am going to close this ticket since the issue is not related to Haxall. If you require further help with building Fantom from source please post on the Fantom forum, or the Fantom Slack group.

**Closed by mgiannini** 2021-07-14 13:57 UTC

**Comment by mgiannini** [comment] 2021-07-15 16:06
FYI - we revereted the change in Haxall that was causing the compile issue. You should be able to compile Haxall now without needing to build Fantom from source.

**Comment by jli113** [comment] 2021-07-17 11:28
'web::WebOutStream.initJs' is gone, but I got another problem, anyway, the docker [image](https://gist.github.com/gtfierro/3c655904100d6abbb3af300127ba8e82) from Gabe solved the problem.
Thanks guys.
